### ISSUE TITLE
Ubuntu 14.04 installation

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/BlocklyDuino#5]
Assigned to @azyth & @kyleoliveira 

Create a clean Ubuntu 14.04 VM and create an installation script for the VM, 
including repo cloning and the installation of all possible dependencies.

In the meantime, the codebender team will create a new VM on AWS, which you will use from now on in order to commit your changes and test your code

**Comment by spiliot** [comment]
The code is merged, will be waiting for you guys to set it up on VM to close this one...

**Comment by azyth** [comment]
I am putting this here since when i try to find the adress for the machine, I keep forgetting where it is. 

The userame you are going to use is "ubuntu".

ssh -i */cornell-blocklyduino-vm.pem ubuntu@blockly.codebender.cc

**Comment by tzikis** [comment]
Soooo, any news on this guys? We can't wait to show the world your work, so we need this :)

**Comment by kyleoliveira** [comment]
We told you guys that it was up when we spoke on Friday, remember? ;)
- Kyle

**Comment by tzikis** [comment]
Oh, sorry guys, I was actually missing in Friday, and I guess I never talked with John and Fotis, so I didn't know about that

I can only see it on my iPad right now, so I can't really use it, but it looks just great!

**Comment by kyleoliveira** [comment]
Can we close this issue now?
